### Assignment: Alternus Vera

- Name: Ravali Nagabandi
- SJSU ID: 011530454
- Team: 3musketeers
- Feature: Hate News

We have identified few below which we can give percentages to - now we need to explain why we have selected these¶
- Political affiliation - Kaggle /Liar -Liar + NYT + Guardian - 26%
- Social Media (yellow press + internet) - https://github.com/KaiDMML/FakeNewsNet + Kaggel dataset - 7%
- Bias - https://github.com/clips/news-audit - 25%
- Hate News - 8%
- Credibility - 24%
- Fact checks https://github.com/sumeetkr/AwesomeFakeNews + dataset in the git link - 10%

#### Hate News:
Sources that actively promote racism, misogyny, homophobia, and other forms of discrimination are observed to be grouped under this category.

References:
1. https://github.com/several27/FakeNewsCorpus
2. https://www.kaggle.com/kernels/notebooks/new?forkParentScriptVersionId=2615953&userName=aarsanjani


#### Following are the datasets explored as part of this project

- Kaggles fake news dataset for Fake news
- NYT API and The Guardian Post API to get real news
- LIAR dataset: https://www.cs.ucsb.edu/william/data/liar_dataset.zip
- BS Detector: https://github.com/bs-detector/bs-detector
- CredBank: compsocial.github.io/CREDBANK-data
- Buzzfeed News: https://github.com/BuzzFeedNews/everything
- Corpus of News on the Web (NOW): https://corpus.byu.edu/now/
- Google trends: https://trends.google.com/trends/
- Click Bait(y) dataset from Kaggle: The Examiner - SpamClickBait News Dataset:    https://www.kaggle.com/therohk/examine-the-examiner
- Click Bait Challenge: https://www.clickbait-challenge.org/#data

In [2]:
import pandas as pd
import csv
import numpy as np
import nltk
from nltk.stem import SnowballStemmer
from nltk.stem.porter import PorterStemmer
from nltk.tokenize import word_tokenize
import seaborn as sb

In [3]:
train_news = pd.read_csv('/Users/ravalinagabandi/Desktop/sjsu/Sem III/Machine Learning/train 2.csv')


In [4]:
#data observation
def data_obs():
    print("training dataset size:")
    print(train_news.shape)
    print(train_news.head(10))


In [5]:
data_obs()

training dataset size:
(159571, 8)
                 id                                       comment_text  toxic  \
0  0000997932d777bf  Explanation\nWhy the edits made under my usern...      0   
1  000103f0d9cfb60f  D'aww! He matches this background colour I'm s...      0   
2  000113f07ec002fd  Hey man, I'm really not trying to edit war. It...      0   
3  0001b41b1c6bb37e  "\nMore\nI can't make any real suggestions on ...      0   
4  0001d958c54c6e35  You, sir, are my hero. Any chance you remember...      0   
5  00025465d4725e87  "\n\nCongratulations from me as well, use the ...      0   
6  0002bcb3da6cb337       COCKSUCKER BEFORE YOU PISS AROUND ON MY WORK      1   
7  00031b1e95af7921  Your vandalism to the Matt Shirvington article...      0   
8  00037261f536c51d  Sorry if the word 'nonsense' was offensive to ...      0   
9  00040093b2687caa  alignment on this subject and which are contra...      0   

   severe_toxic  obscene  threat  insult  identity_hate  
0             0

- Drop unnecessary columns

In [6]:
train_news.drop(train_news.columns[[2,3,4,5,6,7]], axis=1)

id                                       comment_text
0       0000997932d777bf  Explanation\nWhy the edits made under my usern...
1       000103f0d9cfb60f  D'aww! He matches this background colour I'm s...
2       000113f07ec002fd  Hey man, I'm really not trying to edit war. It...
3       0001b41b1c6bb37e  "\nMore\nI can't make any real suggestions on ...
4       0001d958c54c6e35  You, sir, are my hero. Any chance you remember...
5       00025465d4725e87  "\n\nCongratulations from me as well, use the ...
6       0002bcb3da6cb337       COCKSUCKER BEFORE YOU PISS AROUND ON MY WORK
7       00031b1e95af7921  Your vandalism to the Matt Shirvington article...
8       00037261f536c51d  Sorry if the word 'nonsense' was offensive to ...
9       00040093b2687caa  alignment on this subject and which are contra...
10      0005300084f90edc  "\nFair use rationale for Image:Wonju.jpg\n\nT...
11      00054a5e18b50dd4  bbq \n\nbe a man and lets discuss it-maybe ove...
12      0005c987bdfc9d4b  Hey... what is it..\n@ | talk .\nWhat is it......
13      0006f16e4e9f292e  Before you start throwing accusations and warn...
14      00070ef96486d6f9  Oh, and the girl above started her arguments w...
15      00078f8ce7eb276d  "\n\nJuelz Santanas Age\n\nIn 2002, Juelz Sant...
16      0007e25b2121310b  Bye! \n\nDon't look, come or think of comming ...
17      000897889268bc93   REDIRECT Talk:Voydan Pop Georgiev- Chernodrinski
18      0009801bd85e5806  The Mitsurugi point made no sense - why not ar...
19      0009eaea3325de8c  Don't mean to bother you \n\nI see that you're...
20      000b08c464718505  "\n\n Regarding your recent edits \n\nOnce aga...
21      000bfd0867774845  "\nGood to know. About me, yeah, I'm studying ...
22      000c0dfd995809fa  "\n\n Snowflakes are NOT always symmetrical! \...
23      000c6a3f0cd3ba8e  "\n\n The Signpost: 24 September 2012 \n\n Rea...
24      000cfee90f50d471  "\n\nRe-considering 1st paragraph edit?\nI don...
25      000eefc67a2c930f  Radial symmetry \n\nSeveral now extinct lineag...
26      000f35deef84dc4a  There's no need to apologize. A Wikipedia arti...
27      000ffab30195c5e1  Yes, because the mother of the child in the ca...
28      0010307a3a50a353  "\nOk. But it will take a bit of work but I ca...
29      0010833a96e1f886  "== A barnstar for you! ==\n\n  The Real Life ...
...                  ...                                                ...
159541  ffa33d3122b599d6  Your absurd edits \n\nYour absurd edits on gre...
159542  ffa95244f261527f  maybe he's got better things to do than spend ...
159543  ffad104337fe9891  scrap that, it does meet criteria and its gone...
159544  ffaed63c487a2b42                                You could do worse.
159545  ffb268f37788a011  , 7 March 2011 (UTC)\nAre you also User:Bmatts...
159546  ffb47123b2d82762  "\n\nHey listen don't you ever!!!! Delete my e...
159547  ffb7b4c3d3ae5842                     Thank you very, very much.  ·✆
159548  ffb93b0a0a1e78f9                        Talkback: 15 September 2012
159549  ffb998f9749bd83e                         2005 (UTC)\n 06:35, 31 Mar
159550  ffba5332d6b8fd14  i agree/ on another note lil wayne is a talent...
159551  ffbc2db4225258dd  While about half the references are from BYU-I...
159552  ffbcd64a71775e04  Prague Spring \n\nI think that Prague Spring d...
159553  ffbd331a3aa269b9  I see this as having been merged; undoing one ...
159554  ffbdbb0483ed0841  and i'm going to keep posting the stuff u dele...
159555  ffc2f409658571f1  "\n\nHow come when you download that MP3 it's ...
159556  ffc671f2acdd80e1  I'll be on IRC, too, if you have a more specif...
159557  ffc7bbb177c3c966  It is my opinion that that happens to be off-t...
159558  ffca1e81aefc48ac  Please stop removing content from Wikipedia; i...
159559  ffca8d71d71a3fae  Image:Barack-obama-mother.jpg listed for delet...
159560  ffcdcb71854f6d8a  "Editing of article without Consensus & Remova...
159561  ffd2e85b07b3c7e4  "\nNo he did not, read it again (I would hav

In [7]:
#distribution of classes for prediction
def create_distribution(dataFile):
    
    return sb.countplot(x='comment_text', data=dataFile, palette='hls')
   

In [8]:
#create_distribution(train_news)

### Data Preperation


#### Data integrity check (missing label values)

In [9]:
#none of the datasets contains missing values therefore no cleaning required
def data_qualityCheck():
    
    print("Checking data qualitites...")
    train_news.isnull().sum()
    train_news.info()
        
    print("check finished.")

In [10]:
data_qualityCheck()

Checking data qualitites...
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 159571 entries, 0 to 159570
Data columns (total 8 columns):
id               159571 non-null object
comment_text     159571 non-null object
toxic            159571 non-null int64
severe_toxic     159571 non-null int64
obscene          159571 non-null int64
threat           159571 non-null int64
insult           159571 non-null int64
identity_hate    159571 non-null int64
dtypes: int64(6), object(2)
memory usage: 9.7+ MB
check finished.


In [11]:
eng_stemmer = SnowballStemmer('english')

In [12]:
stopwords = set(nltk.corpus.stopwords.words('english'))
stopwords

{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 'r

#### Stemming

In [13]:

def stem_tokens(tokens, stemmer):
    stemmed = []
    for token in tokens:
        stemmed.append(stemmer.stem(token))
    return stemmed

In [14]:
#process the data
def process_data(data,exclude_stopword=True,stem=True):
    tokens = [w.lower() for w in data]
    tokens_stemmed = tokens
    tokens_stemmed = stem_tokens(tokens, eng_stemmer)
    tokens_stemmed = [w for w in tokens_stemmed if w not in stopwords ]
    return tokens_stemmed

In [15]:
processed_data = process_data(train_news['comment_text'],stopwords)
processed_data

["explanation\nwhy the edits made under my username hardcore metallica fan were reverted? they weren't vandalisms, just closure on some gas after i voted at new york dolls fac. and please don't remove the template from the talk page since i'm retired now.89.205.38.27",
 "d'aww! he matches this background colour i'm seemingly stuck with. thanks.  (talk) 21:51, january 11, 2016 (utc)",
 "hey man, i'm really not trying to edit war. it's just that this guy is constantly removing relevant information and talking to me through edits instead of my talk page. he seems to care more about the formatting than the actual info.",
 '"\nmore\ni can\'t make any real suggestions on improvement - i wondered if the section statistics should be later on, or a subsection of ""types of accidents""  -i think the references may need tidying so that they are all in the exact same format ie date format etc. i can do that later on, if no-one else does first - if you have any preferences for formatting style on r

#### Creating ngrams

In [16]:
#unigram 
def create_unigram(words):
    assert type(words) == list
    return words


In [17]:
#bigram
def create_bigrams(words):
    assert type(words) == list
    skip = 0
    join_str = " "
    Len = len(words)
    if Len > 1:
        lst = []
        for i in range(Len-1):
            for k in range(1,skip+2):
                if i+k < Len:
                    lst.append(join_str.join([words[i],words[i+k]]))
    else:
        #set it as unigram
        lst = create_unigram(words)
    return lst

In [18]:
bigrams = create_bigrams(processed_data)
bigrams

["explanation\nwhy the edits made under my username hardcore metallica fan were reverted? they weren't vandalisms, just closure on some gas after i voted at new york dolls fac. and please don't remove the template from the talk page since i'm retired now.89.205.38.27 d'aww! he matches this background colour i'm seemingly stuck with. thanks.  (talk) 21:51, january 11, 2016 (utc)",
 "d'aww! he matches this background colour i'm seemingly stuck with. thanks.  (talk) 21:51, january 11, 2016 (utc) hey man, i'm really not trying to edit war. it's just that this guy is constantly removing relevant information and talking to me through edits instead of my talk page. he seems to care more about the formatting than the actual info.",
 'hey man, i\'m really not trying to edit war. it\'s just that this guy is constantly removing relevant information and talking to me through edits instead of my talk page. he seems to care more about the formatting than the actual info. "\nmore\ni can\'t make any r

#### Tokenize

In [19]:
porter = PorterStemmer()

def tokenizer(text):
    return text.split()

In [20]:
def tokenizer_porter(text):
    return [porter.stem(word) for word in text]

In [21]:
doc = ['You, sir, are my hero. Any chance you remember what page that is on?']

In [22]:
tokenizer_porter(doc)

['you, sir, are my hero. any chance you remember what page that is on?']

### Feature Selection

In [23]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.pipeline import Pipeline
import nltk
import nltk.corpus 
from nltk.tokenize import word_tokenize
from gensim.models.word2vec import Word2Vec

### Bag of words


In [24]:
#we will start with simple bag of words technique 
#creating feature vector - document term matrix
countV = CountVectorizer()
train_count = countV.fit_transform(train_news['comment_text'].values)

print(countV)
print(train_count)


CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)
  (0, 4547)	1
  (0, 5745)	1
  (0, 3513)	1
  (0, 8906)	1
  (0, 118576)	1
  (0, 141537)	1
  (0, 152524)	1
  (0, 123877)	1
  (0, 163071)	1
  (0, 68669)	1
  (0, 164582)	1
  (0, 140200)	1
  (0, 54085)	1
  (0, 129385)	1
  (0, 16261)	1
  (0, 63271)	1
  (0, 53967)	1
  (0, 185894)	1
  (0, 116131)	1
  (0, 20806)	1
  (0, 178500)	1
  (0, 12946)	1
  (0, 70413)	1
  (0, 155005)	1
  (0, 120995)	1
  :	:
  (159570, 141945)	1
  (159570, 82888)	1
  (159570, 82862)	1
  (159570, 94383)	1
  (159570, 22139)	2
  (159570, 40845)	1
  (159570, 142484)	1
  (159570, 72993)	1
  (159570, 172926)	1
  (159570, 22907)	2
  (159570, 78762)	1
  (159570, 3

In [25]:
#print training doc term matrix
#we have matrix of size of (10240, 12196) by calling below
def get_countVectorizer_stats():
    
    #vocab size
    train_count.shape

    #check vocabulary using below command
    print(countV.vocabulary_)

    #get feature names
    print(countV.get_feature_names()[:25])

In [26]:
get_countVectorizer_stats()

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



['00', '000', '0000', '00000', '000000', '0000000', '00000000', '0000000027', '00000001', '00000003', '00000050', '000001', '000002', '000002000004000008000016', '0000030422', '0000035', '000023405011', '00004', '000045', '00007632', '000080', '00008b', '00009c', '0000z', '0001']


### Tf-Idf


In [27]:
#create tf-df frequency features
#tf-idf 
tfidfV = TfidfTransformer()
train_tfidf = tfidfV.fit_transform(train_count)
tfidfV
train_tfidf

<159571x189881 sparse matrix of type '<class 'numpy.float64'>'
	with 6949544 stored elements in Compressed Sparse Row format>

In [28]:
def get_tfidf_stats():
    train_tfidf.shape
    #get train data feature names 
    print(train_tfidf.A[:20])


In [29]:
get_tfidf_stats()

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [30]:
tfidf_ngram = TfidfVectorizer(stop_words='english',ngram_range=(1,4),use_idf=True,smooth_idf=True)
tfidf_ngram

TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 4), norm='l2', preprocessor=None, smooth_idf=True,
        stop_words='english', strip_accents=None, sublinear_tf=False,
        token_pattern='(?u)\\b\\w\\w+\\b', tokenizer=None, use_idf=True,
        vocabulary=None)

In [31]:
#POS Tagging
tagged_sentences = nltk.corpus.treebank.tagged_sents()

cutoff = int(.75 * len(tagged_sentences))
training_sentences = train_news['comment_text']
 
training_sentences.head(10)

0    Explanation\nWhy the edits made under my usern...
1    D'aww! He matches this background colour I'm s...
2    Hey man, I'm really not trying to edit war. It...
3    "\nMore\nI can't make any real suggestions on ...
4    You, sir, are my hero. Any chance you remember...
5    "\n\nCongratulations from me as well, use the ...
6         COCKSUCKER BEFORE YOU PISS AROUND ON MY WORK
7    Your vandalism to the Matt Shirvington article...
8    Sorry if the word 'nonsense' was offensive to ...
9    alignment on this subject and which are contra...
Name: comment_text, dtype: object

In [32]:
training_statement = training_sentences.head(1)
training_statement

0    Explanation\nWhy the edits made under my usern...
Name: comment_text, dtype: object

In [33]:
from sklearn.feature_extraction.text import HashingVectorizer

# create the transform
vectorizer = HashingVectorizer(n_features=5)

# encode document
vector = vectorizer.transform(train_news['comment_text'].values)

# summarize encoded vector
print(vector.shape)
print(vector.toarray())

(159571, 5)
[[-0.2         0.4         0.         -0.8        -0.4       ]
 [-0.83405766 -0.20851441  0.20851441  0.20851441  0.41702883]
 [ 0.39056673  0.52075564  0.52075564  0.39056673  0.39056673]
 ...
 [ 0.         -0.57735027 -0.57735027  0.          0.57735027]
 [-0.28867513  0.         -0.28867513  0.8660254  -0.28867513]
 [ 0.40451992  0.53935989  0.26967994  0.67419986 -0.13483997]]


In [34]:
print(vector.toarray() * 0.08)

[[-0.016       0.032       0.         -0.064      -0.032     ]
 [-0.06672461 -0.01668115  0.01668115  0.01668115  0.03336231]
 [ 0.03124534  0.04166045  0.04166045  0.03124534  0.03124534]
 ...
 [ 0.         -0.04618802 -0.04618802  0.          0.04618802]
 [-0.02309401  0.         -0.02309401  0.06928203 -0.02309401]
 [ 0.03236159  0.04314879  0.0215744   0.05393599 -0.0107872 ]]
